management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    root: INFO


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver